### PR TITLE
Adapt to router changes

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | -

:warning: Merge after: https://github.com/yiisoft/router/pull/128

### CODE REVIEW

**Comment by romkatsu** [comment]
Will you fix the documentation? 

https://github.com/yiisoft/request-model/blob/master/README.md

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
@romkatsu the package isn't dealing with route arguments so there's nothing to fix that I've found.

**Comment by romkatsu** [comment]
@samdark 

here you need to add information about the router is enabled

изображение

**Comment by rustamwin** [comment]
> Will you fix the documentation?


Done, see https://github.com/yiisoft/request-model/pull/31.

**Pull request merged**
